name: CI Check PRs

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  check:
    name: Build and test pull request with ${{ matrix.configuration }} configuration
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration ${{ matrix.configuration }} --no-restore
      - name: Test
        run: dotnet test --configuration ${{ matrix.configuration }} --no-restore --verbosity normal

  dependabot:
    needs: check
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Automatically merge the Dependabot PRs
        run: gh pr merge --auto -r "$PR_URL"